language: rust
rust: stable
os: linux
cache: cargo

branches:
  only:
    - master

install:
  - rustup component add rustfmt
  - rustup component add clippy

script:
  - cargo fmt -- --check
  - cargo clippy
  - cargo build --no-default-features --release
  - cargo build --release
  - cargo test --no-default-features
  - cargo test
  - cargo test --no-default-features --release
  - cargo test --release
  - cargo doc --all --no-deps
