language: rust
rust: stable
os: linux
cache: cargo

branches:
  only:
    - master

install:
  - rustup component add rustfmt
  - rustup component add clippy
  - rustup target add thumbv7em-none-eabihf # for NeoTrellis M4's SAMD51

matrix:
  include:
    - name: rustfmt
      script:
        - cargo fmt -- --check
    - name: clippy
      script:
        - cargo clippy
    - name: build
      script:
        - cargo build --no-default-features --release
        - cargo build --release
    - name: build (thumbv7em-none-eabihf target)
      script:
        - cargo build --target thumbv7em-none-eabihf --no-default-features
        - cargo build --target thumbv7em-none-eabihf --no-default-features --release
    - name: test
      script:
        - cargo test --no-default-features
        - cargo test
        - cargo test --no-default-features --release
        - cargo test --release
    - name: doc build
      script:
        - cargo doc --all --no-deps
